app/app/urls.py
# from django.contrib import admin
from django.urls import path


from users.admin import site
from users.views import main, check_status, add_order, order_success

urlpatterns = [
    path('admin/', site.urls, name="admin"),
    path('', main,name="main"),
    path('status/', check_status, name='check_status'),
    path('add_order/', add_order, name='add_order'),
    path('order_success/', order_success, name='order_success'),

]


# from django.contrib import admin
# from django.urls import path
# from users.admin import site
# from users.views import main
#
# urlpatterns = [
#     path('', main,name="main"),
#     path('admin/', admin.site.urls, name='admin_panel'),
# ]

app/users/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import UserManager as BaseUserManager


class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = models.CharField(_("username"), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True, blank=True)
    objects = UserManager()
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    position = models.ForeignKey(
        'Position',
        related_name='position',
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Position(models.Model):
    name = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name

class RepairOrder(models.Model):
    class Meta:
        verbose_name = 'Repair Order'
        verbose_name_plural = 'Repair Orders'

    user = models.ForeignKey(
        User,
        related_name='users',
        on_delete=models.CASCADE,
        null=True
    )
    Status_CHOICES = {
        "READY": "Готов",
        "IN_PROGRESS": "В работе",
        "ACCEPTED": "Принят",
    }
    status = models.CharField(max_length=70, choices=Status_CHOICES, default="")
    description_device = models.CharField(max_length=300, blank=True)
    price = models.IntegerField(blank=True, null=True)
    date_start = models.DateField(blank=True)
    date_end = models.DateField(blank=True, null=True)
    worker = models.ForeignKey(
        User,
        related_name='worker',
        on_delete=models.CASCADE,
        null=True
    )
    repair_code = models.IntegerField(blank=True, null=True, unique=True)

class SpareParts(models.Model):
    class Meta:
        verbose_name = 'Spare Part'
        verbose_name_plural = 'Spare Parts'
    name = models.CharField(max_length=200, blank=True)
    count = models.IntegerField(blank=True)
    price_for_1 = models.FloatField(blank=True)
    description = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name

class PurchaseOrder(models.Model):
    class Meta:
        verbose_name = 'Purchase Order'
        verbose_name_plural = 'Purchase Orders'
    description_device_or_detail = models.CharField(max_length=300, blank=True)
    amount = models.IntegerField(blank=True)
    date_create = models.DateField(blank=True)
    date_supplies = models.DateField(blank=True)
    provider = models.CharField(max_length=100, blank=True)
    price = models.FloatField(blank=True)

    def __str__(self):
        return self.description_device_or_detail

class StorySpareParts(models.Model):
    class Meta:
        verbose_name = 'Story Spare Part'
        verbose_name_plural = 'Story Spare Parts'
    spare_parts = models.ForeignKey(
        SpareParts,
        related_name='spare_parts',
        on_delete=models.CASCADE,
        null=True
    )
    user = models.ForeignKey(
        User,
        related_name='users_Story_spare_parts_user',
        on_delete=models.CASCADE,
        null=True
    )
    EMERGENCE_CHOICES = {
        "SUPPLY": "Поставка",
        "REPAIR": "Ремонт",
        "MARRIAGE": "Брак",
    }
    emergence = models.CharField(max_length=70, choices=EMERGENCE_CHOICES, default="")
    count = models.IntegerField(blank=True)
    description = models.CharField(max_length=200, blank=True)
    timestamp = models.DateField(blank=True)

app/users/forms.py
from django import forms
from .models import RepairOrder

class RepairOrderForm(forms.ModelForm):
    class Meta:
        model = RepairOrder
        fields = ['user', 'description_device', 'date_start', 'worker',]

app/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import RepairOrder
from .forms import RepairOrderForm

def main(request):
    return render(request,"main.html",)

def order_success(request):
    return render(request, 'order_success.html')



def check_status(request):
    repair_code = request.GET.get('repair_code')
    repair_order = None

    if repair_code:
        try:
            repair_order = RepairOrder.objects.get(repair_code=repair_code)
        except RepairOrder.DoesNotExist:
            repair_order = None

    return render(request, 'check_status.html', {'repair_order': repair_order, 'repair_code': repair_code})

def add_order(request):
    if request.method == "POST":
        form = RepairOrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('order_success')
    else:
        form = RepairOrderForm()

    return render(request, 'add_order.html', {'form': form})

app/templates/add_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавление заказа на ремонт</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h1 class="text-center mb-4">Добавление заказа на ремонт</h1>
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                {{ form.user.label_tag }}<br>
                                {{ form.user }}
                            </div>

                            <div class="mb-3">
                                {{ form.description_device.label_tag }}<br>
                                {{ form.description_device }}
                            </div>
                            <div class="mb-3">
                                {{ form.date_start.label_tag }}<br>
                                {{ form.date_start }}
                            </div>
                            <div class="mb-3">
                                {{ form.worker.label_tag }}<br>
                                {{ form.worker }}
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Добавить заказ</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybAsDf1E1p1UOpI7Wt2l1UIMq58fl1h3qyyM4f6MITu8jKZgk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Uc4rdWZZFfjIKZCw7KJx6ih7E1LMtYJ6DkLg6Nuvo5N3cZ" crossorigin="anonymous"></script>
</body>
</html>

app/templates/check_status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Проверка статуса ремонта</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
    <div class="container mt-5">
        <h1 class="text-center">Проверка статуса ремонта</h1>
        <form method="get" class="row g-3 mt-4 justify-content-center">
            <div class="col-auto">
                <label for="repair_code" class="visually-hidden">Код ремонта:</label>
                <input type="text" class="form-control" id="repair_code" name="repair_code" placeholder="Код ремонта" required>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary mb-3">Проверить статус</button>
            </div>
        </form>

        {% if repair_code and not repair_order %}
            <div class="alert alert-danger text-center mt-4" role="alert">
                Заказ с кодом {{ repair_code }} не найден.
            </div>
        {% elif repair_order %}
            <div class="card mt-4">
                <div class="card-header">
                    Информация о ремонте
                </div>
                <div class="card-body">
                    <p><strong>Код ремонта:</strong> {{ repair_order.repair_code }}</p>
                    <p><strong>Статус:</strong> {{ repair_order.get_status_display }}</p>
                    <p><strong>Описание устройства:</strong> {{ repair_order.description_device }}</p>
                    <p><strong>Дата начала:</strong> {{ repair_order.date_start }}</p>
                    <p><strong>Дата окончания:</strong> {{ repair_order.date_end }}</p>
                    <p><strong>Цена:</strong> {{ repair_order.price }}</p>
                </div>
            </div>
        {% endif %}
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/order_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Submitted</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Заказ успешно отправлен</h5>
                <a  href="{% url 'main' %}" class="btn btn-primary">На главную</a>
            </div>
        </div>
    </div>
</body>
</html>